name: 'Set OPAM environment variables'
description: 'Runs "opam env" and extends the environment for subsequent steps (via $GITHUB_ENV)'
inputs:
  switch:
    description: 'Name of desired OPAM switch, leave blank for default'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run script and extend env
      shell: bash
      run: opam-env-bare.sh ${{ inputs.switch }} >>$GITHUB_ENV

    # Setting PATH in GITHUB_ENV has no effect. 
    # This step pulls the PATH component and appends
    # it $GITHUB_PATH.
    - name: Hack for PATH
      shell: bash
      run: |
        eval $(PATH= $(which opam) env ${{ inputs.switch }})
        echo $PATH >>$GITHUB_PATH
