name: 'Set OPAM environment variables'
description: 'Runs "opam env" and extends the environment for subsequent steps (via $GITHUB_ENV)'
inputs:
  output:
    description: 'The file where to append the output, usually $GITHUB_ENV'
    required: true
  switch:
    description: 'Name of desired OPAM switch, leave blank for default'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run script and append to env
      shell: bash
      run: opam-env-bare.sh ${{ inputs.switch }} >>$GITHUB_ENV
